version: 0.0
os: linux
files:
  - source: /
    destination: /data/pipeline
permissions:
  - object: /data/pipeline
    owner: ec2-user
    mode: 766
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/after.sh
      runas: ec2-user
